# Generated by Django 5.1.6 on 2025-03-01 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='producttranslation',
            table='product_translation',
        ),
    ]
