# Generated by Django 5.1.6 on 2025-03-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_product_app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_image",
            field=models.ImageField(blank=True, null=True, upload_to="media_photos/"),
        ),
    ]
