# Generated by Django 5.1.6 on 2025-03-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_product_app', '0003_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='halal_status',
            field=models.CharField(choices=[('Halal', 'Halal'), ('Haram', 'Haram'), ('Mashbooh', 'Mashbooh'), ('Unknown', 'Unknown')], default='Unknown', max_length=10),
        ),
    ]
