# Generated by Django 5.1.6 on 2025-05-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_product_app', '0003_remove_product_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
