# Generated by Django 5.1.6 on 2025-05-16 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_product_app', '0004_product_product_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['translations__product_category_name']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_category_name',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='shop',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='_product_app.productcategory'),
        ),
    ]
