# Generated by Django 5.1.6 on 2025-05-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_product_app', '0006_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='shop',
        ),
    ]
