# Generated by Django 5.1.6 on 2025-05-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_product_app', '0007_remove_productcategory_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_availability',
            field=models.CharField(choices=[('available', 'Available'), ('non-available', 'Non-Available')], default='available', max_length=15),
        ),
    ]
