# Generated by Django 5.1.6 on 2025-05-27 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_product_app', '0008_product_product_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_availability',
        ),
    ]
