# Generated by Django 5.1.6 on 2025-05-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_product_app', '0009_remove_product_product_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_availability',
            field=models.CharField(choices=[('available', 'Available'), ('non-available', 'Non-Available')], default='available', max_length=15),
        ),
    ]
