# Generated by Django 5.1.6 on 2025-05-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_product_app', '0011_productvariant'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productvariant',
            table='product_variant',
        ),
    ]
