# Generated by Django 5.1.6 on 2025-05-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_product_app', '0012_alter_productvariant_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Jumlah stok semua varian'),
        ),
        migrations.AlterModelTable(
            name='productvariant',
            table=None,
        ),
    ]
