# Generated by Django 5.1.6 on 2025-05-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_product_app', '0013_alter_product_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productvariant',
            table='product_variant',
        ),
    ]
