# Generated by Django 5.1.6 on 2025-05-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_product_app', '0014_alter_productvariant_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productimage',
            table='product_image',
        ),
    ]
