# Generated by Django 5.1.6 on 2025-05-28 15:03

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_product_app', '0015_alter_productimage_table'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('variants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
