# Generated by Django 5.1.6 on 2025-05-28 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_product_app', '0016_alter_product_managers_productvariant_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
    ]
