# Generated by Django 5.1.6 on 2025-05-30 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_product_app', '0017_alter_product_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='is_active',
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='product_images',
        ),
    ]
