# Generated by Django 5.1.6 on 2025-06-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_product_app', '0019_productvariant_is_active_productvariant_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_variant',
            field=models.BooleanField(default=True),
        ),
    ]
