# Generated by Django 5.1.6 on 2025-06-02 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_product_app', '0020_product_no_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_quantity',
        ),
    ]
