# Generated by Django 5.1.6 on 2025-06-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_product_app', '0021_remove_product_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_quantity',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Jumlah stok semua varian'),
        ),
    ]
