# Generated by Django 5.1.6 on 2025-05-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_customer_app', '0004_rename_street_shippingaddress_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='Malaysia', max_length=100),
        ),
    ]
