# Generated by Django 5.1.6 on 2025-05-04 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_customer_app', '0005_alter_shippingaddress_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='postcode',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='street',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to='_customer_app.customer'),
        ),
    ]
