# Generated by Django 5.1.6 on 2025-05-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_customer_app', '0007_alter_shippingaddress_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='street',
            new_name='address_line1',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
