# Generated by Django 5.1.6 on 2025-05-27 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_customer_app', '0008_rename_street_shippingaddress_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shippingaddress',
            table='shipping_address',
        ),
    ]
