# Generated by Django 5.1.6 on 2025-02-14 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_seller_app', '0002_alter_seller_options_alter_seller_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('restaurant_name', models.CharField(max_length=50)),
                ('restaurant_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('restaurant_logo', models.ImageField(blank=True, null=True, upload_to='media_photos/')),
                ('restaurant_bg_photo', models.ImageField(blank=True, null=True, upload_to='media_photos/')),
                ('restaurant_status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('P', 'Pending')], default='P', max_length=1)),
                ('restaurant_desc', models.TextField(blank=True, max_length=250, null=True)),
                ('restaurant_category', models.CharField(blank=True, max_length=50, null=True)),
                ('restaurant_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('restaurant_delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_seller_app.seller')),
            ],
            options={
                'db_table': 'restaurant',
            },
        ),
    ]
