# Generated by Django 5.1.6 on 2025-02-27 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_seller_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('shop_logo', models.ImageField(default='media_photos/anonymousUserAvatar.jpeg', upload_to='media_photos/')),
                ('shop_bg_photo', models.ImageField(default='media_photos/anonymousUserAvatar.jpeg', upload_to='media_photos/')),
                ('shop_status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('P', 'Pending')], default='P', max_length=1)),
                ('shop_desc', models.TextField(blank=True, max_length=250, null=True)),
                ('shop_category', models.CharField(blank=True, max_length=50, null=True)),
                ('shop_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('shop_delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_seller_app.seller')),
            ],
            options={
                'db_table': 'shop',
            },
        ),
    ]
