# Generated by Django 5.1.6 on 2025-02-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_bg_photo',
            field=models.ImageField(upload_to='media_photos/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_logo',
            field=models.ImageField(upload_to='media_photos/'),
        ),
    ]
