# Generated by Django 5.1.6 on 2025-05-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='shop_category',
        ),
        migrations.AddField(
            model_name='shop',
            name='delivery_price_type',
            field=models.CharField(choices=[('admin', 'Follow admin base price'), ('custom', 'Use my own flat fee')], default='admin', max_length=6),
        ),
    ]
