# Generated by Django 5.1.6 on 2025-03-01 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_seller_app', '0001_initial'),
        ('_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_seller_app.seller'),
        ),
    ]
