# Generated by Django 5.1.6 on 2025-05-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_shop_app', '0002_remove_shop_shop_category_shop_delivery_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
