# Generated by Django 5.1.6 on 2025-03-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("_shop_app", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="shop_country",
        ),
    ]
