# Generated by Django 5.1.6 on 2025-02-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='user',
        ),
    ]
