# Generated by Django 5.1.6 on 2025-02-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_authentication_app', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='image_avatars/'),
        ),
    ]
