# Generated by Django 5.1.6 on 2025-06-15 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_delivery_app', '0002_alter_deliverymethod_table_alter_shopdelivery_table'),
        ('_order_app', '0001_initial'),
        ('_shop_app', '0004_alter_shop_shop_delivery_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_surcharge',
        ),
        migrations.AlterField(
            model_name='order',
            name='eta_max',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='eta_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_delivery_app.deliverymethod'),
        ),
        migrations.CreateModel(
            name='OrderShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='_delivery_app.deliverymethod')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippings', to='_order_app.order')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='_shop_app.shop')),
            ],
            options={
                'unique_together': {('order', 'shop')},
            },
        ),
    ]
