# Generated by Django 5.1.6 on 2025-06-16 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_order_app', '0003_alter_ordershipping_method'),
        ('_transaction_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='_transaction_app.transaction'),
        ),
    ]
