# Generated by Django 5.1.6 on 2025-06-16 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_delivery_app', '0002_alter_deliverymethod_table_alter_shopdelivery_table'),
        ('_order_app', '0005_transaction_alter_order_transaction'),
        ('_product_app', '0022_product_product_price_product_product_quantity'),
        ('_shop_app', '0004_alter_shop_shop_delivery_fee'),
        ('_transaction_app', '0003_alter_transaction_amount_alter_transaction_bill_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='_transaction_app.transaction'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_with_method', to='_delivery_app.deliverymethod'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='_product_app.productvariant'),
        ),
        migrations.AlterField(
            model_name='ordershipping',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_entries', to='_delivery_app.deliverymethod'),
        ),
        migrations.AlterField(
            model_name='ordershipping',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_shippings', to='_shop_app.shop'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
