# Generated by Django 5.1.6 on 2025-06-16 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_customer_app', '0009_alter_shippingaddress_table'),
        ('_order_app', '0006_alter_order_transaction_alter_order_shipping_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='_customer_app.shippingaddress'),
        ),
    ]
