# Generated by Django 5.1.6 on 2025-06-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_order_app', '0007_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('FAILED', 'Payment Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
    ]
