# Generated by Django 5.1.6 on 2025-05-07 10:34

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('seller_id', models.CharField(max_length=8, unique=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('business_license', models.FileField(upload_to='file_business_licenses/')),
            ],
            options={
                'db_table': 'seller',
            },
            bases=('_user_app.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
