# Generated by Django 5.1.6 on 2025-05-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_seller_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Nombor akaun bank.', max_length=30),
        ),
        migrations.AddField(
            model_name='seller',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Nama bank untuk pembayaran.', max_length=100),
        ),
    ]
