# Generated by Django 5.1.6 on 2025-02-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_seller_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='business_license',
            field=models.FileField(upload_to='file_business_licenses/'),
        ),
    ]
