# Generated by Django 5.1.6 on 2025-02-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_seller_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={},
        ),
        migrations.AlterModelTable(
            name='seller',
            table='seller',
        ),
    ]
