# Generated by Django 5.1.6 on 2025-05-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_seller_app', '0003_alter_seller_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='bank_account_holder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
