# Generated by Django 5.1.6 on 2025-05-17 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('est_day_min', models.PositiveSmallIntegerField()),
                ('est_day_max', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShopDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_delivery_app.deliverymethod')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_shop_app.shop')),
            ],
            options={
                'verbose_name': 'Shop delivery option',
                'verbose_name_plural': 'Shop delivery options',
                'unique_together': {('shop', 'method')},
            },
        ),
    ]
