# Generated by Django 5.1.6 on 2025-05-17 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deliverymethod',
            table='delivery_method',
        ),
        migrations.AlterModelTable(
            name='shopdelivery',
            table='shop_delivery',
        ),
    ]
