# Generated by Django 5.1.6 on 2025-06-16 15:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_transaction_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bill_code',
            field=models.CharField(blank=True, help_text='BillCode from ToyyibPay', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(default='toyyibpay', help_text='Payment gateway identifier', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', help_text='Current status of the transaction', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal unique transaction reference', unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
