# Generated by Django 5.1.6 on 2025-06-16 16:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_transaction_app', '0002_transaction_bill_code_alter_transaction_gateway_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bill_code',
            field=models.CharField(blank=True, help_text='ToyyibPay BillCode', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(default='toyyibpay', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
